apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-metricsapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-metricsapi
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/r1-productcatalog/metrics"
        prometheus.io/port: "4000"
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-metricsapi
        version: lesterthomas-metricsapi-latest
    spec:
      containers:
      - name: {{.Release.Name}}-registerallevents
        image: lesterthomas/registerallevents:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}           
        imagePullPolicy: Always
        ports:
        - name: {{.Release.Name}}-prapi
          containerPort: 4000
         
